### ISSUE TITLE
Less popular tags do not have history after mid-2018?

### ISSUE THREAD

**Issue by mnalis** [tyrasd/taghistory#34]
It seems that tags with less than about 1000 uses contain history only to about mid-2018, not after that.
After 2018, only dashed line to current value is shown. 

Is that intentional? If so, it should be documented.

e.g. https://taghistory.raifer.tech/#***/shop/fishmonger&***/amenity/gambling&***/amenity/crematorium&***/amenity/exhibition_centre&***/amenity/emergency_service&***/amenity/vehicle_ramp&***/shop/hobby&***/shop/vacuum_cleaner produces:

![taghistory_min](https://github.com/tyrasd/taghistory/assets/156656/39f8b609-4fc2-4831-9342-40b105820f54)

I found related only this [diary comment](https://www.openstreetmap.org/user/tyr_asd/diary/39402#comment48633), but it seems to talk about taginfo history being limited to more popular values, not taghistory.

- There are related strangeness in taghistory database in that mid-2018 timeframe too, e.g. https://github.com/tyrasd/taghistory/issues/33

**Comment by matkoniecz** [comment]
> Is that intentional? If so, it should be documented.

Data was last processed in 2018 and not updates since then, for popular ones taginfo api data is shown - but that is missing for rare ones

**Comment by mnalis** [comment]
> Data was last processed in 2018 and not updates since then, for popular ones taginfo api data is shown - but that is missing for rare ones

Thanks, I've now  tried to clarify that in wiki https://wiki.openstreetmap.org/wiki/OSM_Tag_History#Missing_data_for_less_popular_tags, feel free to improve

**Comment by tyrasd** [comment]
The data behind the taghistory API was updated today to a the state approx 1 week ago (i.e. which was the latest available history planet file had).

![taghistory(4)](https://github.com/tyrasd/taghistory/assets/1927298/0a6a8364-01b5-4e2d-82ed-303057e883c6)

Since taginfo provides 90+% of the most relevant tag history information and the face that as this is unfortunately still quite a bit of manual effort for me, I will still only do this every couple of years or so.

**Comment by matkoniecz** [comment]
Thanks so much for update! It is especially useful to track down what happened with tags formerly with high use and nowadays with a really low one.
